Machine.add(me.dir(-1) + "Utility.ck");
Machine.add(me.dir(-1) + "ModeQuantizer.ck");
Machine.add(me.dir(-1) + "/clock/Clock.ck");
Machine.add(me.dir(-1) + "/clock/InternalClock.ck");
Machine.add(me.dir(-1) + "/clock/Metronome.ck");
Machine.add(me.dir(-1) + "Sequencer.ck");
Machine.add(me.dir(-1) + "PitchSequencer.ck");
Machine.add(me.dir(0) + "LividBase.ck");
Machine.add(me.dir(0) + "LividStep.ck");
